require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoardWhensController do

  # This should return the minimal set of attributes required to create a valid
  # BoardWhen. As you add validations to BoardWhen, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "board" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoardWhensController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all board_whens as @board_whens" do
      board_when = BoardWhen.create! valid_attributes
      get :index, {}, valid_session
      assigns(:board_whens).should eq([board_when])
    end
  end

  describe "GET show" do
    it "assigns the requested board_when as @board_when" do
      board_when = BoardWhen.create! valid_attributes
      get :show, {:id => board_when.to_param}, valid_session
      assigns(:board_when).should eq(board_when)
    end
  end

  describe "GET new" do
    it "assigns a new board_when as @board_when" do
      get :new, {}, valid_session
      assigns(:board_when).should be_a_new(BoardWhen)
    end
  end

  describe "GET edit" do
    it "assigns the requested board_when as @board_when" do
      board_when = BoardWhen.create! valid_attributes
      get :edit, {:id => board_when.to_param}, valid_session
      assigns(:board_when).should eq(board_when)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BoardWhen" do
        expect {
          post :create, {:board_when => valid_attributes}, valid_session
        }.to change(BoardWhen, :count).by(1)
      end

      it "assigns a newly created board_when as @board_when" do
        post :create, {:board_when => valid_attributes}, valid_session
        assigns(:board_when).should be_a(BoardWhen)
        assigns(:board_when).should be_persisted
      end

      it "redirects to the created board_when" do
        post :create, {:board_when => valid_attributes}, valid_session
        response.should redirect_to(BoardWhen.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved board_when as @board_when" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoardWhen.any_instance.stub(:save).and_return(false)
        post :create, {:board_when => { "board" => "invalid value" }}, valid_session
        assigns(:board_when).should be_a_new(BoardWhen)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoardWhen.any_instance.stub(:save).and_return(false)
        post :create, {:board_when => { "board" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested board_when" do
        board_when = BoardWhen.create! valid_attributes
        # Assuming there are no other board_whens in the database, this
        # specifies that the BoardWhen created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BoardWhen.any_instance.should_receive(:update_attributes).with({ "board" => "" })
        put :update, {:id => board_when.to_param, :board_when => { "board" => "" }}, valid_session
      end

      it "assigns the requested board_when as @board_when" do
        board_when = BoardWhen.create! valid_attributes
        put :update, {:id => board_when.to_param, :board_when => valid_attributes}, valid_session
        assigns(:board_when).should eq(board_when)
      end

      it "redirects to the board_when" do
        board_when = BoardWhen.create! valid_attributes
        put :update, {:id => board_when.to_param, :board_when => valid_attributes}, valid_session
        response.should redirect_to(board_when)
      end
    end

    describe "with invalid params" do
      it "assigns the board_when as @board_when" do
        board_when = BoardWhen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoardWhen.any_instance.stub(:save).and_return(false)
        put :update, {:id => board_when.to_param, :board_when => { "board" => "invalid value" }}, valid_session
        assigns(:board_when).should eq(board_when)
      end

      it "re-renders the 'edit' template" do
        board_when = BoardWhen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoardWhen.any_instance.stub(:save).and_return(false)
        put :update, {:id => board_when.to_param, :board_when => { "board" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested board_when" do
      board_when = BoardWhen.create! valid_attributes
      expect {
        delete :destroy, {:id => board_when.to_param}, valid_session
      }.to change(BoardWhen, :count).by(-1)
    end

    it "redirects to the board_whens list" do
      board_when = BoardWhen.create! valid_attributes
      delete :destroy, {:id => board_when.to_param}, valid_session
      response.should redirect_to(board_whens_url)
    end
  end

end
